name: Build

# Run this on pushes to `nightly`, or when a pull request is opened against `nightly`
on:
  push:
    branches:
    - nightly
  pull_request:
    branches:
    - nightly

jobs:
  test:
    name: Test on Rust ${{ matrix.rust }}
    runs-on: ubuntu-latest

    strategy:
      matrix:
        rust:
          - nightly

    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Install Rust Toolchain
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: ${{ matrix.rust }}
          override: true
          components: rustfmt, clippy

      - name: Build
        uses: actions-rs/cargo@v1
        with:
          command: build

      - name: Check Format
        uses: actions-rs/cargo@v1
        with:
          command: fmt
          args: --all -- --check

      - name: Lint
        uses: actions-rs/cargo@v1
        with:
          command: clippy
          args: --all --all-targets --all-features

      - name: Test
        uses: actions-rs/cargo@v1
        with:
          command: test
